# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ template "ethereum.fullname" . }}-geth-tx-data-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 40Gi
    # apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: {{ template "ethereum.fullname" . }}-geth-tx-data
# spec:
#   capacity:
#     storage: 30Gi
#   accessModes:
#   - "ReadWriteOnce"
#   persistentVolumeReclaimPolicy: "Retain"
#   storageClassName: "local-storage"
#   local:
#     path: "/mnt/disks/ssd0"
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: "kubernetes.io/hostname"
  #         operator: "In"
  #         values: "gke-test-cluster-default-pool-926ddf80-f166"
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd